language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      mono: latest
      dotnet: 1.0.0-preview2-003121
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      mono: latest
      dotnet: 1.0.0-preview2-003121

script:
  - ./build.sh GenerateDocs

cache:
  directories:
  - packages
  - $HOME/.local/share/NuGet

